FROM python:3.10.9-slim-buster
WORKDIR game_xo
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Настройка приложения
ENV LOGGING_LEVEL="DEBUG"
ENV LOGGING_GURU="1"
ENV HOST="0.0.0.0"
ENV PORT=8004

# Настройка Postgres
ENV POSTGRES__DB=""
ENV POSTGRES__USER=""
ENV POSTGRES__PASSWORD=""
ENV POSTGRES__HOST="host.docker.internal"
ENV POSTGRES__PORT=5432
ENV POSTGRES__DB_SCHEMA="game_xo"

# Настройка Apispec
ENV APISPEC__TITLE="Игра Крестики Ноилики"
ENV APISPEC__SWAGGER_PATH="/"

RUN pip install --upgrade pip  --no-cache-dir
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY game_xo .
CMD python main.py
