"""First migration

Revision ID: 4a63c1b11069
Revises: 
Create Date: 2023-03-31 18:56:46.550922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a63c1b11069'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='game_sapper'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_user_id'),
    schema='game_sapper'
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('cords', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sapper.game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='game_sapper'
    )
    op.create_table('user_game_session',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sapper.game_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_sapper.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_session_id'),
    schema='game_sapper'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_session', schema='game_sapper')
    op.drop_table('rounds', schema='game_sapper')
    op.drop_table('users', schema='game_sapper')
    op.drop_table('game_sessions', schema='game_sapper')
    # ### end Alembic commands ###
