name: Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo
        run: echo "🎉 Checkout - OK"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Echo
        run: echo "🎉 Set up QEMU - OK"
      - name: Set up Docker Builder
        uses: docker/setup-buidx-action@v2
      - name: Echo
        run: echo "🎉 Set up Docker Builder - OK"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Echo
        run: echo "🎉 Login to Docker Hub - OK"
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: dockerfile_game_sapper
          push: true
          tags: user/app:latest
      - name: Echo
        run: echo "🎉 Build and push - OK"